version: "3.8"

services:
    majiup:
        image: waziupiot/majiup:latest
        environment:
            - TEST_VAR=1
        ports:
            - "8082:8082"
        restart: always
        command: ["./majiup"]
        network_mode: "host"

networks:
    default:
        external:
            name: wazigate
